### ISSUE TITLE
className overrides not working properly

### ISSUE THREAD

**Issue by pyyding** [juneHQ/charts#31]
Currently we're relying on custom `cx` method to add styles to composable components.

This method doesn't properly support className overrides. 

The order of classes in HTML does in fact **not** allow overriding 😂

Simplest fix without thinking too hard is using [tailwind-merge](https://github.com/dcastil/tailwind-merge) inside cx

**Comment by ferrucc-io** [comment]
Good point let's start using it!

**Comment by pyyding** [comment]
Almost made the PR for `tailwind-merge` when I realised we are introducing style conflicts for consumers

When building `@june-so/ui`, we're exporting the tailwind styles our library components use. Meaning for consumers that use tailwind, they would have two separate stylesheets of tailwind classes. One would override the other depending on stylesheet injection order.

And their styles are different than ours
- their blue-500 could be different than ui lib's blue-500, 
- their font-sm could be different than ui libs font-sm
- the sizings could be different, border radiuses, etc.

To resolve the conflicts, we should introduce a [custom prefix](https://tailwindcss.com/docs/configuration#prefix). 

(Probably should find a way to add a prefix automatically during build not manually adding them to the template [maybe with this](https://www.npmjs.com/package/postcss-prefix-selector)).

After introducing a custom prefix, there's no use for `tailwind-merge` anymore. We do need to communicate in docs to import june styles before local styles.

This would resolve the conflicts for the build but Storybook would require a separate tailwind setup (unless we don't override styles in storybook examples)

The other way around all this would be to make june ui a copy-paste library like shadcn ui or catalyst

**Comment by ferrucc-io** [comment]
Makes sense to me! make the prefix something like june-ui-

**Comment by pyyding** [comment]
I changed my mind again 😄

**Can't easily auto-add prefixes on build**
On top of rewriting class names in css, would have to try to find every classname in js and rewrite js. Easier to use a prefix in template. I don't think we wanna build that processor at this point.

related:
- https://github.com/tailwindlabs/tailwindcss/issues/1746

**We don't want to use prefixes in template during development**
- Prevents people from copy-pasting components to their own tailwind projects.
- Locks june-ui into being a "install-only" lib
- even longer & uglier classes

**Just use tailwind merge**
If consumer's tailwind styles are different, so be it. It's basically out of the box configuration if they're using tailwind.

to make june-so/ui themeable, would make sense to define library specific color palette and avoid using `gray-500` etc.

**Comment by ferrucc-io** [comment]
I think we should rely on the tailwind color configuration for themeing, I like what tremor did where they rely on tailwind css to use the library
